class gcpm::params {
  $config_dir   = lookup('config_dir',   { default_value => ''})
  $oatuh_file   = lookup('oatuh_file',   { default_value => ''})
  $service_account_file = lookup('service_account_file', { default_value => ''})
  $project      = lookup('project',      { default_value => 'fill-your-project'})
  $zone         = lookup('zone',         { default_value => 'asia-northeast1-b'})
  $machines     = lookup('machines',     { merge => unique, default_value => []})
  $max_cores    = lookup('max_cores',    { default_value => 0})
  $static_wns   = lookup('static_wns'    { merge => unique, default_value => []})
  $prefix       = lookup('prefix',       { default_value => 'gcp-wn'})
  $preemptible  = lookup('preemptible',  { default_value => 0})
  $off_timer    = lookup('off_timer',    { default_value => 0})
  $network_tag  = lookup('network_tag',  { merge => unique , default_value => []})
  $reuse        = lookup('reuse',        { default_value => 0})
  $interval     = lookup('interval',     { default_value => 10})
  $head_info    = lookup('head_info',    { default_value => 'gcp'})
  $head         = lookup('head',         { default_value => ''})
  $port         = lookup('port',         { default_value => 9618})
  $domain       = lookup('domain',       { default_value => ''})
  $admin        = lookup('admin',        { default_value => ''})
  $owner        = lookup('owner',        { default_value => 'Condor Owner'})
  $wait_cmd     = lookup('wait_cmd',     { default_value => 0})
  $bucket       = lookup('bucket',       { default_value => ''})
  $storageClass = lookup('storageClass', { default_value => 'REGIONAL'})
  $location     = lookup('location',     { default_value => ''})
  $log_file     = lookup('log_file',     { default_value => ''})
  $log_level    = lookup('log_level',    { default_value => 'info'})
  $service      = lookup('service',      { default_value => true})
}
